# train
TRAIN_BATCH_SIZE: 64
VAL_BATCH_SIZE: 64
RESOLUTION: 480
LR: 0.0001
NUM_WORKERS: 12
EPOCHS: 200
TRAIN_PRINT: 100
VAL_PRINT: 100
SEED: 2

# model
MODEL: 'sidebranch_detector'
ENCODER_WEIGHTS: 

# post processing
NMS_IOU: 0.05
CONF_THRESH: 0.8
RPN_FG_IOU_THRESH: 0.5
RPN_BG_IOU_THRESH: 0.5
PRE_NMS_TOP_N_TEST: 4
TTA: False

# data
DATA_ROOT: '../Data/'
DATASET: 'sidebranch'
MODALITY: 'ivus'
NUM_CLASSES: 2
INPUT_DIM: 1
AUGMENTATION: True